apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: b31p3n6bc-python 
  janus-idp.io/tekton: b31p3n6bc-python
  backstage.io/kubernetes-id: b31p3n6bc-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b31p3n6bc-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml